# Generated by Django 5.2.3 on 2025-06-28 13:23

import django.db.models.deletion
from django.conf import settings
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('pontualidade', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pontualidade (%)')),
                ('participacao_aula', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Participação em aula (%)')),
                ('entregas_tarefas', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Entregas de tarefas (%)')),
                ('comportamento_funcionarios', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Comportamento com funcionários (%)')),
                ('participacao_oficinas', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Participação em oficinas (%)')),
                ('comportamento_sala', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Comportamento em sala de aula (%)')),
                ('participacao_plataformas', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Participação em plataformas (%)')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('prazo', models.DateField()),
                ('anexos', models.FileField(blank=True, null=True, upload_to='anexos/')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('serie', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('pontualidade', models.PositiveIntegerField(default=0, verbose_name='Pontualidade (%)')),
                ('participacao_aula', models.PositiveIntegerField(default=0, verbose_name='Participação em aula (%)')),
                ('entregas_tarefas', models.PositiveIntegerField(default=0, verbose_name='Entregas de tarefas (%)')),
                ('comportamento_funcionarios', models.PositiveIntegerField(default=0, verbose_name='Comportamento com funcionários (%)')),
                ('participacao_oficinas', models.PositiveIntegerField(default=0, verbose_name='Participação em oficinas (%)')),
                ('comportamento_sala', models.PositiveIntegerField(default=0, verbose_name='Comportamento em sala de aula (%)')),
                ('participacao_plataformas', models.PositiveIntegerField(default=0, verbose_name='Participação em plataformas (%)')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edutrack.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('PROVA', 'Prova'), ('TRABALHO', 'Trabalho'), ('ATIVIDADE', 'Atividade')], default='ATIVIDADE', max_length=20, verbose_name='Tipo de Atividade')),
                ('data_entrega', models.DateTimeField(verbose_name='Data e Hora de Entrega')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição/Observações')),
                ('entregue', models.BooleanField(default=False, verbose_name='Entregue')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='edutrack.aluno', verbose_name='Aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrack.disciplina', verbose_name='Disciplina')),
            ],
            options={
                'ordering': ['data_entrega'],
            },
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrack.atividade')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas_chat', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas_chat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=255)),
                ('corpo', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas_mensagem', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas_mensagem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.FloatField(blank=True, null=True)),
                ('nota2', models.FloatField(blank=True, null=True)),
                ('nota3', models.FloatField(blank=True, null=True)),
                ('media', models.FloatField(blank=True, null=True)),
                ('recuperacao', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrack.professor', verbose_name='Professor'),
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrack.aluno')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrack.professor')),
                ('nota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edutrack.nota')),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_contato', models.CharField(blank=True, max_length=20)),
                ('filhos', models.ManyToManyField(to='edutrack.aluno', verbose_name='Filhos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Resumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('links', models.URLField(blank=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrack.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('ranking', models.TextField(blank=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrack.turma')),
            ],
        ),
        migrations.CreateModel(
            name='ConteudoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('links', models.URLField(blank=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrack.turma')),
            ],
        ),
        migrations.CreateModel(
            name='GradeHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira')], max_length=3)),
                ('horario', models.CharField(choices=[('1', '08:00 - 09:00'), ('2', '09:00 - 10:00'), ('3', '10:00 - 11:00'), ('4', '11:00 - 12:00'), ('5', '13:00 - 14:00'), ('6', '14:00 - 15:00'), ('7', '15:00 - 16:00')], max_length=1)),
                ('disciplina', models.CharField(max_length=100)),
                ('sala', models.CharField(blank=True, max_length=50)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrack.turma')),
            ],
            options={
                'verbose_name': 'Grade de Horário',
                'verbose_name_plural': 'Grades de Horário',
                'ordering': ['dia_semana', 'horario'],
                'constraints': [models.UniqueConstraint(fields=('turma', 'dia_semana', 'horario'), name='unique_grade')],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('serie', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrack.atividade')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrack.professor'),
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrack.aluno')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrack.professor')),
                ('nota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edutrack.nota')),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_contato', models.CharField(blank=True, max_length=20)),
                ('filhos', models.ManyToManyField(to='edutrack.aluno', verbose_name='Filhos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Resumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('links', models.URLField(blank=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrack.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('ranking', models.TextField(blank=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrack.turma')),
            ],
        ),
        migrations.CreateModel(
            name='ConteudoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('links', models.URLField(blank=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrack.turma')),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrack.turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edutrack.turma'),
        ),
        migrations.CreateModel(
            name='GradeHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira')], max_length=3)),
                ('horario', models.CharField(choices=[('1', '08:00 - 09:00'), ('2', '09:00 - 10:00'), ('3', '10:00 - 11:00'), ('4', '11:00 - 12:00'), ('5', '13:00 - 14:00'), ('6', '14:00 - 15:00'), ('7', '15:00 - 16:00')], max_length=1)),
                ('disciplina', models.CharField(max_length=100)),
                ('sala', models.CharField(blank=True, max_length=50)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrack.turma')),
            ],
            options={
                'verbose_name': 'Grade de Horário',
                'verbose_name_plural': 'Grades de Horário',
                'ordering': ['dia_semana', 'horario'],
                'constraints': [models.UniqueConstraint(fields=('turma', 'dia_semana', 'horario'), name='unique_grade')],
            },
        ),
    ]
