# Generated by Django 5.2.3 on 2025-07-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edutrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='recuperacao',
            field=models.FloatField(blank=True, null=True, verbose_name='Recuperação'),
        ),
    ]
