# Generated by Django 5.2.3 on 2025-06-27 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edutrack', '0003_responsavel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='nota',
            name='recuperacao',
        ),
        migrations.AddField(
            model_name='nota',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edutrack.aluno', verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='comportamento_funcionarios',
            field=models.PositiveIntegerField(default=0, verbose_name='Comportamento com funcionários (%)'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='comportamento_sala',
            field=models.PositiveIntegerField(default=0, verbose_name='Comportamento em sala de aula (%)'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='entregas_tarefas',
            field=models.PositiveIntegerField(default=0, verbose_name='Entregas de tarefas (%)'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='participacao_aula',
            field=models.PositiveIntegerField(default=0, verbose_name='Participação em aula (%)'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='participacao_oficinas',
            field=models.PositiveIntegerField(default=0, verbose_name='Participação em oficinas (%)'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='participacao_plataformas',
            field=models.PositiveIntegerField(default=0, verbose_name='Participação em plataformas (%)'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='pontualidade',
            field=models.PositiveIntegerField(default=0, verbose_name='Pontualidade (%)'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='media',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edutrack.disciplina', verbose_name='Disciplina'),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('PROVA', 'Prova'), ('TRABALHO', 'Trabalho'), ('ATIVIDADE', 'Atividade')], default='ATIVIDADE', max_length=20, verbose_name='Tipo de Atividade')),
                ('data_entrega', models.DateTimeField(verbose_name='Data e Hora de Entrega')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição/Observações')),
                ('entregue', models.BooleanField(default=False, verbose_name='Entregue')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='edutrack.aluno', verbose_name='Aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrack.disciplina', verbose_name='Disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrack.professor', verbose_name='Professor')),
            ],
            options={
                'ordering': ['data_entrega'],
            },
        ),
    ]
