# Generated by Django 5.2.3 on 2025-06-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('turma', models.CharField(max_length=50, verbose_name='Turma')),
            ],
        ),
    ]
