# Generated by Django 5.2.3 on 2025-06-12 03:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='comportamento_funcionarios',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Comportamento com funcionários (%)'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='comportamento_sala',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Comportamento em sala de aula (%)'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='entregas_tarefas',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Entregas de tarefas (%)'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='participacao_aula',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Participação em aula (%)'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='participacao_oficinas',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Participação em oficinas (%)'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='participacao_plataformas',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Participação em plataformas (%)'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='pontualidade',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pontualidade (%)'),
        ),
    ]
